# PyTorch 101

Zewei Chu zeweichu@gmail.com

Reference
- https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
- https://pytorch.org/tutorials/beginner/pytorch_with_examples.html


What is PyTorch?
================

PyTorch is a Python library for scientific computing. 

- Similar to NumPy，but it can use GPUs
- Define and train deep learning models

Tensors
---------------


Tensor is similar to NumPy ndarray，but it can be used on GPUs


In [1]:
from __future__ import print_function
import torch

uninitialized 5x3 tensor

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.7339e+30, 1.4347e-19],
        [2.7909e+23, 1.8037e+28, 1.7237e+25],
        [9.1041e-12, 6.2609e+22, 4.7428e+30],
        [3.8001e-39, 0.0000e+00, 0.0000e+00]])


random tensor:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4821, 0.3854, 0.8517],
        [0.7962, 0.0632, 0.5409],
        [0.8891, 0.6112, 0.7829],
        [0.0715, 0.8069, 0.2608],
        [0.3292, 0.0119, 0.2759]])


all 0 type long tensor:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


construct tensor from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


use an existing tensor to construct another tensor

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4793, -2.4772,  0.9738],
        [ 2.0328,  1.3981,  1.7509],
        [-0.7931, -0.0291, -0.6803],
        [-1.2944, -0.7352, -0.9346],
        [ 0.5917, -0.5149, -1.8149]])


tensor shape:

In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` returns a tuple</p></div>

Operations

addition



In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.7113, -1.5490,  1.4009],
        [ 2.4590,  1.6504,  2.6889],
        [-0.3609,  0.4950, -0.3357],
        [-0.5029, -0.3086, -0.1498],
        [ 1.2850, -0.3189, -0.8868]])


another way of addition


In [9]:
print(torch.add(x, y))

tensor([[ 1.7113, -1.5490,  1.4009],
        [ 2.4590,  1.6504,  2.6889],
        [-0.3609,  0.4950, -0.3357],
        [-0.5029, -0.3086, -0.1498],
        [ 1.2850, -0.3189, -0.8868]])


addition：output as parameter

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.7113, -1.5490,  1.4009],
        [ 2.4590,  1.6504,  2.6889],
        [-0.3609,  0.4950, -0.3357],
        [-0.5029, -0.3086, -0.1498],
        [ 1.2850, -0.3189, -0.8868]])


in-place addition

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.7113, -1.5490,  1.4009],
        [ 2.4590,  1.6504,  2.6889],
        [-0.3609,  0.4950, -0.3357],
        [-0.5029, -0.3086, -0.1498],
        [ 1.2850, -0.3189, -0.8868]])


<div class="alert alert-info"><h4>Note</h4><p>all in-place operation end with ``_``.
    For example：``x.copy_(y)``, ``x.t_()``, changes ``x``.</p></div>

indexing similar to numpy. 


In [12]:
print(x[:, 1])

tensor([-2.4772,  1.3981, -0.0291, -0.7352, -0.5149])


Resizing: resize/reshape a tensor，use ``torch.view``：

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If a tensor only contains one element，use``.item()`` to change the value to Python number。

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4726])
0.4726296067237854


**More readings**


  All Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers
  `<https://pytorch.org/docs/torch>`.

Numpy and Tensor conversion
------------

Torch Tensor and NumPy ndarray share the same memory

Change Torch Tensor to NumPy ndarray


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


change numpy array value

In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


convert NumPy ndarray to Torch Tensor

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All CPU Tensors can be converted to numpy ndarray or the other way around. 

CUDA Tensors
------------

use ``.to`` method to move a tensor. 



In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


Warmup: Two layer neural network with PyTorch
--------------

A Fully connected ReLU neural network，one hidden layer，no bias。Predict y from x，using L2 loss.

- Define a model
- Define a loss function
- Define an optimizer

In the loop
- Forward pass
- Backward pass
- Update model parameters


In [1]:
import torch

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Use the nn package to define our model and loss function.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)
loss_fn = torch.nn.MSELoss(reduction='sum')

# Use the optim package to define an Optimizer that will update the weights of
# the model for us. Here we will use Adam; the optim package contains many other
# optimization algoriths. The first argument to the Adam constructor tells the
# optimizer which Tensors it should update.
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
for t in range(500):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute and print loss.
    loss = loss_fn(y_pred, y)
    print(t, loss.item())

    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables it will update (which are the learnable
    # weights of the model). This is because by default, gradients are
    # accumulated in buffers( i.e, not overwritten) whenever .backward()
    # is called. Checkout docs of torch.autograd.backward for more details.
    optimizer.zero_grad()

    # Backward pass: compute gradient of the loss with respect to model
    # parameters
    loss.backward()

    # Calling the step function on an Optimizer makes an update to its
    # parameters
    optimizer.step()

0 561.5958862304688
1 545.87353515625
2 530.6712646484375
3 515.9916381835938
4 501.74395751953125
5 487.8907775878906
6 474.56939697265625
7 461.6273193359375
8 449.07305908203125
9 436.8492736816406
10 424.98455810546875
11 413.4566345214844
12 402.30096435546875
13 391.5439453125
14 381.0994567871094
15 370.91217041015625
16 361.02935791015625
17 351.465087890625
18 342.2153015136719
19 333.2441101074219
20 324.53460693359375
21 316.0675048828125
22 307.8112487792969
23 299.773681640625
24 291.93377685546875
25 284.34765625
26 276.9891357421875
27 269.8183898925781
28 262.87286376953125
29 256.13177490234375
30 249.56944274902344
31 243.17298889160156
32 236.9014892578125
33 230.75050354003906
34 224.71298217773438
35 218.7852783203125
36 212.99038696289062
37 207.34033203125
38 201.82313537597656
39 196.42190551757812
40 191.18215942382812
41 186.0736541748047
42 181.08627319335938
43 176.2286376953125
44 171.4801788330078
45 166.85467529296875
46 162.34368896484375
47 157.93566894

404 3.3039741538232192e-06
405 3.0831788535579108e-06
406 2.8768417905666865e-06
407 2.683774027900654e-06
408 2.503695668565342e-06
409 2.3349857656285167e-06
410 2.177150236093439e-06
411 2.030225232374505e-06
412 1.8930395526695065e-06
413 1.7648090988586773e-06
414 1.644832877900626e-06
415 1.5332310567828245e-06
416 1.4287473959484487e-06
417 1.3310235544850002e-06
418 1.2403091886881157e-06
419 1.155504151029163e-06
420 1.0762040574263665e-06
421 1.00240970368759e-06
422 9.334121955362207e-07
423 8.689949027029797e-07
424 8.089444918368827e-07
425 7.531369305979752e-07
426 7.009850833128439e-07
427 6.523551974169095e-07
428 6.070384870326961e-07
429 5.646850809171156e-07
430 5.254432835499756e-07
431 4.88858688640903e-07
432 4.5467868403648026e-07
433 4.227719045957201e-07
434 3.931059495698719e-07
435 3.656043077171489e-07
436 3.39804785198794e-07
437 3.1586318982590456e-07
438 2.934252165687212e-07
439 2.728019694586692e-07
440 2.5332928998977877e-07
441 2.3546476768387947e-07


# FizzBuzz

FizzBuzz is a simple game. The rule is as follows: Count from 1 onward, every time we see a multiple of 3, say "fizz", when we see multiple of 5, say "buzz", when we see multiple of 15, say "fizzbuzz". 


In [2]:
# One-hot encode the desired outputs: [number, "fizz", "buzz", "fizzbuzz"]
def fizz_buzz_encode(i):
    if   i % 15 == 0: return 3
    elif i % 5  == 0: return 2
    elif i % 3  == 0: return 1
    else:             return 0
    
def fizz_buzz_decode(i, prediction):
    return [str(i), "fizz", "buzz", "fizzbuzz"][prediction]

print(fizz_buzz_decode(1, fizz_buzz_encode(1)))
print(fizz_buzz_decode(2, fizz_buzz_encode(2)))
print(fizz_buzz_decode(5, fizz_buzz_encode(5)))
print(fizz_buzz_decode(12, fizz_buzz_encode(12)))
print(fizz_buzz_decode(15, fizz_buzz_encode(15)))

1
2
buzz
fizz
fizzbuzz


Define model input and output

In [3]:
import numpy as np
import torch

NUM_DIGITS = 10

# Represent each input by an array of its binary digits.
def binary_encode(i, num_digits):
    return np.array([i >> d & 1 for d in range(num_digits)])

trX = torch.Tensor([binary_encode(i, NUM_DIGITS) for i in range(101, 2 ** NUM_DIGITS)])
trY = torch.LongTensor([fizz_buzz_encode(i) for i in range(101, 2 ** NUM_DIGITS)])

Define a PyTorch model

In [4]:
# Define the model
NUM_HIDDEN = 100
model = torch.nn.Sequential(
    torch.nn.Linear(NUM_DIGITS, NUM_HIDDEN),
    torch.nn.ReLU(),
    torch.nn.Linear(NUM_HIDDEN, 4)
)

In [5]:
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.05)

In [6]:
# Start training it
BATCH_SIZE = 128
for epoch in range(10000):
    for start in range(0, len(trX), BATCH_SIZE):
        end = start + BATCH_SIZE
        batchX = trX[start:end]
        batchY = trY[start:end]

        y_pred = model(batchX)
        loss = loss_fn(y_pred, batchY)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Find loss on training data
    loss = loss_fn(model(trX), trY).item()
    print('Epoch:', epoch, 'Loss:', loss)

Epoch: 0 Loss: 1.2004950046539307
Epoch: 1 Loss: 1.1640883684158325
Epoch: 2 Loss: 1.1527522802352905
Epoch: 3 Loss: 1.1481730937957764
Epoch: 4 Loss: 1.1459331512451172
Epoch: 5 Loss: 1.1446384191513062
Epoch: 6 Loss: 1.1437804698944092
Epoch: 7 Loss: 1.1431453227996826
Epoch: 8 Loss: 1.142640471458435
Epoch: 9 Loss: 1.1422098875045776
Epoch: 10 Loss: 1.1418375968933105
Epoch: 11 Loss: 1.1415038108825684
Epoch: 12 Loss: 1.1412063837051392
Epoch: 13 Loss: 1.1409330368041992
Epoch: 14 Loss: 1.140678882598877
Epoch: 15 Loss: 1.1404379606246948
Epoch: 16 Loss: 1.1402066946029663
Epoch: 17 Loss: 1.139994502067566
Epoch: 18 Loss: 1.1397907733917236
Epoch: 19 Loss: 1.1395955085754395
Epoch: 20 Loss: 1.1394075155258179
Epoch: 21 Loss: 1.1392297744750977
Epoch: 22 Loss: 1.1390554904937744
Epoch: 23 Loss: 1.1388884782791138
Epoch: 24 Loss: 1.138728380203247
Epoch: 25 Loss: 1.1385706663131714
Epoch: 26 Loss: 1.1384234428405762
Epoch: 27 Loss: 1.138276219367981
Epoch: 28 Loss: 1.138135313987732
E

Epoch: 257 Loss: 1.0809606313705444
Epoch: 258 Loss: 1.0801191329956055
Epoch: 259 Loss: 1.0807079076766968
Epoch: 260 Loss: 1.0795364379882812
Epoch: 261 Loss: 1.078857660293579
Epoch: 262 Loss: 1.0796377658843994
Epoch: 263 Loss: 1.0786036252975464
Epoch: 264 Loss: 1.0776382684707642
Epoch: 265 Loss: 1.0784562826156616
Epoch: 266 Loss: 1.077485203742981
Epoch: 267 Loss: 1.0765990018844604
Epoch: 268 Loss: 1.077317237854004
Epoch: 269 Loss: 1.0775295495986938
Epoch: 270 Loss: 1.0767228603363037
Epoch: 271 Loss: 1.0751421451568604
Epoch: 272 Loss: 1.0743533372879028
Epoch: 273 Loss: 1.0744742155075073
Epoch: 274 Loss: 1.0733637809753418
Epoch: 275 Loss: 1.0739808082580566
Epoch: 276 Loss: 1.0726702213287354
Epoch: 277 Loss: 1.073151707649231
Epoch: 278 Loss: 1.0719146728515625
Epoch: 279 Loss: 1.072623610496521
Epoch: 280 Loss: 1.0712684392929077
Epoch: 281 Loss: 1.0700448751449585
Epoch: 282 Loss: 1.0714094638824463
Epoch: 283 Loss: 1.070117473602295
Epoch: 284 Loss: 1.069044113159179

Epoch: 505 Loss: 0.8755696415901184
Epoch: 506 Loss: 0.8735800981521606
Epoch: 507 Loss: 0.8730010390281677
Epoch: 508 Loss: 0.8714472651481628
Epoch: 509 Loss: 0.8703666925430298
Epoch: 510 Loss: 0.8690623044967651
Epoch: 511 Loss: 0.868593692779541
Epoch: 512 Loss: 0.8665676116943359
Epoch: 513 Loss: 0.8653947710990906
Epoch: 514 Loss: 0.8635125160217285
Epoch: 515 Loss: 0.8630408048629761
Epoch: 516 Loss: 0.8621096014976501
Epoch: 517 Loss: 0.8608749508857727
Epoch: 518 Loss: 0.859901487827301
Epoch: 519 Loss: 0.8588904142379761
Epoch: 520 Loss: 0.857082188129425
Epoch: 521 Loss: 0.8563538789749146
Epoch: 522 Loss: 0.8542473912239075
Epoch: 523 Loss: 0.852999210357666
Epoch: 524 Loss: 0.8516285419464111
Epoch: 525 Loss: 0.8508536219596863
Epoch: 526 Loss: 0.8500279784202576
Epoch: 527 Loss: 0.8486765027046204
Epoch: 528 Loss: 0.8476024270057678
Epoch: 529 Loss: 0.8461812734603882
Epoch: 530 Loss: 0.8448161482810974
Epoch: 531 Loss: 0.8437885046005249
Epoch: 532 Loss: 0.8423540592193

Epoch: 746 Loss: 0.5914965271949768
Epoch: 747 Loss: 0.5896608829498291
Epoch: 748 Loss: 0.5885770916938782
Epoch: 749 Loss: 0.5869698524475098
Epoch: 750 Loss: 0.5861650705337524
Epoch: 751 Loss: 0.5863391757011414
Epoch: 752 Loss: 0.584690272808075
Epoch: 753 Loss: 0.5837488770484924
Epoch: 754 Loss: 0.582686722278595
Epoch: 755 Loss: 0.5813016295433044
Epoch: 756 Loss: 0.5803118944168091
Epoch: 757 Loss: 0.5793425440788269
Epoch: 758 Loss: 0.5782652497291565
Epoch: 759 Loss: 0.5777263641357422
Epoch: 760 Loss: 0.5763819217681885
Epoch: 761 Loss: 0.5763288736343384
Epoch: 762 Loss: 0.5748264193534851
Epoch: 763 Loss: 0.5732308030128479
Epoch: 764 Loss: 0.5724092721939087
Epoch: 765 Loss: 0.5724691152572632
Epoch: 766 Loss: 0.5704510807991028
Epoch: 767 Loss: 0.5693557262420654
Epoch: 768 Loss: 0.5684517621994019
Epoch: 769 Loss: 0.5683084726333618
Epoch: 770 Loss: 0.5669390559196472
Epoch: 771 Loss: 0.5654494166374207
Epoch: 772 Loss: 0.5647450685501099
Epoch: 773 Loss: 0.56318914890

Epoch: 973 Loss: 0.40180703997612
Epoch: 974 Loss: 0.40081629157066345
Epoch: 975 Loss: 0.4004042148590088
Epoch: 976 Loss: 0.39942169189453125
Epoch: 977 Loss: 0.39958834648132324
Epoch: 978 Loss: 0.3982449173927307
Epoch: 979 Loss: 0.3979494869709015
Epoch: 980 Loss: 0.39762231707572937
Epoch: 981 Loss: 0.39654213190078735
Epoch: 982 Loss: 0.3955685496330261
Epoch: 983 Loss: 0.3953458368778229
Epoch: 984 Loss: 0.3944619596004486
Epoch: 985 Loss: 0.3938218951225281
Epoch: 986 Loss: 0.3936006426811218
Epoch: 987 Loss: 0.3926142752170563
Epoch: 988 Loss: 0.39172133803367615
Epoch: 989 Loss: 0.39138299226760864
Epoch: 990 Loss: 0.3910222053527832
Epoch: 991 Loss: 0.39037665724754333
Epoch: 992 Loss: 0.38951602578163147
Epoch: 993 Loss: 0.3892683684825897
Epoch: 994 Loss: 0.38783976435661316
Epoch: 995 Loss: 0.3879619240760803
Epoch: 996 Loss: 0.38699081540107727
Epoch: 997 Loss: 0.3862299621105194
Epoch: 998 Loss: 0.3855307102203369
Epoch: 999 Loss: 0.3858078718185425
Epoch: 1000 Loss: 0

Epoch: 1228 Loss: 0.2704920768737793
Epoch: 1229 Loss: 0.2704585790634155
Epoch: 1230 Loss: 0.26955199241638184
Epoch: 1231 Loss: 0.2690894603729248
Epoch: 1232 Loss: 0.269286572933197
Epoch: 1233 Loss: 0.26854392886161804
Epoch: 1234 Loss: 0.26828083395957947
Epoch: 1235 Loss: 0.2675900161266327
Epoch: 1236 Loss: 0.2672578990459442
Epoch: 1237 Loss: 0.2671547532081604
Epoch: 1238 Loss: 0.26630571484565735
Epoch: 1239 Loss: 0.26604771614074707
Epoch: 1240 Loss: 0.2657102048397064
Epoch: 1241 Loss: 0.26565882563591003
Epoch: 1242 Loss: 0.2648424506187439
Epoch: 1243 Loss: 0.26450997591018677
Epoch: 1244 Loss: 0.2642589807510376
Epoch: 1245 Loss: 0.2637016177177429
Epoch: 1246 Loss: 0.2634008526802063
Epoch: 1247 Loss: 0.26331809163093567
Epoch: 1248 Loss: 0.2626935541629791
Epoch: 1249 Loss: 0.26209500432014465
Epoch: 1250 Loss: 0.2618170380592346
Epoch: 1251 Loss: 0.26160159707069397
Epoch: 1252 Loss: 0.26139765977859497
Epoch: 1253 Loss: 0.26086536049842834
Epoch: 1254 Loss: 0.2603244

Epoch: 1448 Loss: 0.20179927349090576
Epoch: 1449 Loss: 0.20130552351474762
Epoch: 1450 Loss: 0.201095312833786
Epoch: 1451 Loss: 0.2009437084197998
Epoch: 1452 Loss: 0.20062246918678284
Epoch: 1453 Loss: 0.2005862593650818
Epoch: 1454 Loss: 0.200191468000412
Epoch: 1455 Loss: 0.19992905855178833
Epoch: 1456 Loss: 0.19973719120025635
Epoch: 1457 Loss: 0.1994951367378235
Epoch: 1458 Loss: 0.19946502149105072
Epoch: 1459 Loss: 0.1989651918411255
Epoch: 1460 Loss: 0.1987442523241043
Epoch: 1461 Loss: 0.1984594762325287
Epoch: 1462 Loss: 0.19851583242416382
Epoch: 1463 Loss: 0.1981794536113739
Epoch: 1464 Loss: 0.1978912204504013
Epoch: 1465 Loss: 0.19770507514476776
Epoch: 1466 Loss: 0.19730567932128906
Epoch: 1467 Loss: 0.19707448780536652
Epoch: 1468 Loss: 0.19703514873981476
Epoch: 1469 Loss: 0.19668780267238617
Epoch: 1470 Loss: 0.19634057581424713
Epoch: 1471 Loss: 0.1962030827999115
Epoch: 1472 Loss: 0.1959056407213211
Epoch: 1473 Loss: 0.19584205746650696
Epoch: 1474 Loss: 0.195537

Epoch: 1673 Loss: 0.15731243789196014
Epoch: 1674 Loss: 0.1570490598678589
Epoch: 1675 Loss: 0.1569119244813919
Epoch: 1676 Loss: 0.1568102091550827
Epoch: 1677 Loss: 0.15665045380592346
Epoch: 1678 Loss: 0.1564032882452011
Epoch: 1679 Loss: 0.15641260147094727
Epoch: 1680 Loss: 0.1561436951160431
Epoch: 1681 Loss: 0.15589044988155365
Epoch: 1682 Loss: 0.15578827261924744
Epoch: 1683 Loss: 0.15568946301937103
Epoch: 1684 Loss: 0.15553933382034302
Epoch: 1685 Loss: 0.15535233914852142
Epoch: 1686 Loss: 0.15531472861766815
Epoch: 1687 Loss: 0.15511521697044373
Epoch: 1688 Loss: 0.15484963357448578
Epoch: 1689 Loss: 0.15476585924625397
Epoch: 1690 Loss: 0.15458425879478455
Epoch: 1691 Loss: 0.15434309840202332
Epoch: 1692 Loss: 0.15434888005256653
Epoch: 1693 Loss: 0.15412269532680511
Epoch: 1694 Loss: 0.15397244691848755
Epoch: 1695 Loss: 0.15396209061145782
Epoch: 1696 Loss: 0.15360595285892487
Epoch: 1697 Loss: 0.153499037027359
Epoch: 1698 Loss: 0.15328000485897064
Epoch: 1699 Loss: 0

Epoch: 1904 Loss: 0.12647731602191925
Epoch: 1905 Loss: 0.12650229036808014
Epoch: 1906 Loss: 0.12625707685947418
Epoch: 1907 Loss: 0.1261516660451889
Epoch: 1908 Loss: 0.1260989010334015
Epoch: 1909 Loss: 0.1259397566318512
Epoch: 1910 Loss: 0.1257961541414261
Epoch: 1911 Loss: 0.12575802206993103
Epoch: 1912 Loss: 0.12557421624660492
Epoch: 1913 Loss: 0.12550166249275208
Epoch: 1914 Loss: 0.12543459236621857
Epoch: 1915 Loss: 0.1252458244562149
Epoch: 1916 Loss: 0.12529222667217255
Epoch: 1917 Loss: 0.12509429454803467
Epoch: 1918 Loss: 0.12495672702789307
Epoch: 1919 Loss: 0.12488658726215363
Epoch: 1920 Loss: 0.12473297119140625
Epoch: 1921 Loss: 0.12457989901304245
Epoch: 1922 Loss: 0.12456794828176498
Epoch: 1923 Loss: 0.1244153380393982
Epoch: 1924 Loss: 0.12432088702917099
Epoch: 1925 Loss: 0.12421689182519913
Epoch: 1926 Loss: 0.12407103925943375
Epoch: 1927 Loss: 0.12396671622991562
Epoch: 1928 Loss: 0.1239384114742279
Epoch: 1929 Loss: 0.12378436326980591
Epoch: 1930 Loss: 0

Epoch: 2146 Loss: 0.10375981777906418
Epoch: 2147 Loss: 0.10363464802503586
Epoch: 2148 Loss: 0.10354683548212051
Epoch: 2149 Loss: 0.10350704193115234
Epoch: 2150 Loss: 0.1033884659409523
Epoch: 2151 Loss: 0.10329202562570572
Epoch: 2152 Loss: 0.1032036691904068
Epoch: 2153 Loss: 0.10315960645675659
Epoch: 2154 Loss: 0.10304893553256989
Epoch: 2155 Loss: 0.10301538556814194
Epoch: 2156 Loss: 0.10287223756313324
Epoch: 2157 Loss: 0.10277256369590759
Epoch: 2158 Loss: 0.10273224115371704
Epoch: 2159 Loss: 0.10261044651269913
Epoch: 2160 Loss: 0.10255000740289688
Epoch: 2161 Loss: 0.10243121534585953
Epoch: 2162 Loss: 0.10241127759218216
Epoch: 2163 Loss: 0.10230717062950134
Epoch: 2164 Loss: 0.10223817825317383
Epoch: 2165 Loss: 0.10215152055025101
Epoch: 2166 Loss: 0.10209421068429947
Epoch: 2167 Loss: 0.10204941779375076
Epoch: 2168 Loss: 0.10191433131694794
Epoch: 2169 Loss: 0.10182921588420868
Epoch: 2170 Loss: 0.10175038874149323
Epoch: 2171 Loss: 0.10168666392564774
Epoch: 2172 Lo

Epoch: 2366 Loss: 0.08786986023187637
Epoch: 2367 Loss: 0.08773836493492126
Epoch: 2368 Loss: 0.08770815283060074
Epoch: 2369 Loss: 0.08763536810874939
Epoch: 2370 Loss: 0.08755699545145035
Epoch: 2371 Loss: 0.08753544092178345
Epoch: 2372 Loss: 0.08743058145046234
Epoch: 2373 Loss: 0.08737928420305252
Epoch: 2374 Loss: 0.08730257302522659
Epoch: 2375 Loss: 0.0872543528676033
Epoch: 2376 Loss: 0.08719522505998611
Epoch: 2377 Loss: 0.08712413907051086
Epoch: 2378 Loss: 0.08706343173980713
Epoch: 2379 Loss: 0.08701858669519424
Epoch: 2380 Loss: 0.08695495873689651
Epoch: 2381 Loss: 0.08687764406204224
Epoch: 2382 Loss: 0.08681391179561615
Epoch: 2383 Loss: 0.0867265835404396
Epoch: 2384 Loss: 0.08667211979627609
Epoch: 2385 Loss: 0.08663492649793625
Epoch: 2386 Loss: 0.08658164739608765
Epoch: 2387 Loss: 0.08648491650819778
Epoch: 2388 Loss: 0.08645240217447281
Epoch: 2389 Loss: 0.08636871725320816
Epoch: 2390 Loss: 0.08633938431739807
Epoch: 2391 Loss: 0.08623665571212769
Epoch: 2392 Lo

Epoch: 2594 Loss: 0.07470957934856415
Epoch: 2595 Loss: 0.07465161383152008
Epoch: 2596 Loss: 0.07462255656719208
Epoch: 2597 Loss: 0.07454922050237656
Epoch: 2598 Loss: 0.0744604617357254
Epoch: 2599 Loss: 0.07445672154426575
Epoch: 2600 Loss: 0.07439141720533371
Epoch: 2601 Loss: 0.0743279755115509
Epoch: 2602 Loss: 0.07425835728645325
Epoch: 2603 Loss: 0.07421740144491196
Epoch: 2604 Loss: 0.07417461276054382
Epoch: 2605 Loss: 0.07410182058811188
Epoch: 2606 Loss: 0.07407157123088837
Epoch: 2607 Loss: 0.07402234524488449
Epoch: 2608 Loss: 0.07391627877950668
Epoch: 2609 Loss: 0.07390294969081879
Epoch: 2610 Loss: 0.07382677495479584
Epoch: 2611 Loss: 0.07378780096769333
Epoch: 2612 Loss: 0.0737493485212326
Epoch: 2613 Loss: 0.07366383820772171
Epoch: 2614 Loss: 0.07362756133079529
Epoch: 2615 Loss: 0.0735757052898407
Epoch: 2616 Loss: 0.07352214306592941
Epoch: 2617 Loss: 0.07346412539482117
Epoch: 2618 Loss: 0.07340895384550095
Epoch: 2619 Loss: 0.07336076349020004
Epoch: 2620 Loss

Epoch: 2838 Loss: 0.06316427141427994
Epoch: 2839 Loss: 0.06313220411539078
Epoch: 2840 Loss: 0.0630820095539093
Epoch: 2841 Loss: 0.06304220855236053
Epoch: 2842 Loss: 0.06298940628767014
Epoch: 2843 Loss: 0.06293197721242905
Epoch: 2844 Loss: 0.06290043890476227
Epoch: 2845 Loss: 0.06286249309778214
Epoch: 2846 Loss: 0.06280482560396194
Epoch: 2847 Loss: 0.06278638541698456
Epoch: 2848 Loss: 0.06272310018539429
Epoch: 2849 Loss: 0.0627017691731453
Epoch: 2850 Loss: 0.06265369057655334
Epoch: 2851 Loss: 0.06261138617992401
Epoch: 2852 Loss: 0.06258557736873627
Epoch: 2853 Loss: 0.06252338737249374
Epoch: 2854 Loss: 0.06248108670115471
Epoch: 2855 Loss: 0.06243434548377991
Epoch: 2856 Loss: 0.0623868852853775
Epoch: 2857 Loss: 0.06235794723033905
Epoch: 2858 Loss: 0.06230247765779495
Epoch: 2859 Loss: 0.06226976215839386
Epoch: 2860 Loss: 0.062238890677690506
Epoch: 2861 Loss: 0.06220104172825813
Epoch: 2862 Loss: 0.06214990094304085
Epoch: 2863 Loss: 0.062101978808641434
Epoch: 2864 L

Epoch: 3081 Loss: 0.05374002829194069
Epoch: 3082 Loss: 0.05371644347906113
Epoch: 3083 Loss: 0.05367192253470421
Epoch: 3084 Loss: 0.05364295467734337
Epoch: 3085 Loss: 0.05359819903969765
Epoch: 3086 Loss: 0.0535728745162487
Epoch: 3087 Loss: 0.05354175716638565
Epoch: 3088 Loss: 0.05350498855113983
Epoch: 3089 Loss: 0.05348765850067139
Epoch: 3090 Loss: 0.05344824492931366
Epoch: 3091 Loss: 0.05340337008237839
Epoch: 3092 Loss: 0.05336727574467659
Epoch: 3093 Loss: 0.05332159996032715
Epoch: 3094 Loss: 0.0533023439347744
Epoch: 3095 Loss: 0.05328945815563202
Epoch: 3096 Loss: 0.05323314294219017
Epoch: 3097 Loss: 0.05320565402507782
Epoch: 3098 Loss: 0.05314753204584122
Epoch: 3099 Loss: 0.05312754213809967
Epoch: 3100 Loss: 0.05310435965657234
Epoch: 3101 Loss: 0.053062476217746735
Epoch: 3102 Loss: 0.05302578955888748
Epoch: 3103 Loss: 0.05300835520029068
Epoch: 3104 Loss: 0.05297872796654701
Epoch: 3105 Loss: 0.052937690168619156
Epoch: 3106 Loss: 0.0529119148850441
Epoch: 3107 L

Epoch: 3308 Loss: 0.046745166182518005
Epoch: 3309 Loss: 0.04673668369650841
Epoch: 3310 Loss: 0.046693578362464905
Epoch: 3311 Loss: 0.04668532311916351
Epoch: 3312 Loss: 0.04664119333028793
Epoch: 3313 Loss: 0.04662886634469032
Epoch: 3314 Loss: 0.04658988118171692
Epoch: 3315 Loss: 0.04655739292502403
Epoch: 3316 Loss: 0.04652925580739975
Epoch: 3317 Loss: 0.04650333896279335
Epoch: 3318 Loss: 0.04647484049201012
Epoch: 3319 Loss: 0.04646570608019829
Epoch: 3320 Loss: 0.046434808522462845
Epoch: 3321 Loss: 0.04639381170272827
Epoch: 3322 Loss: 0.046377263963222504
Epoch: 3323 Loss: 0.04634958505630493
Epoch: 3324 Loss: 0.046308282762765884
Epoch: 3325 Loss: 0.04628683999180794
Epoch: 3326 Loss: 0.04625392332673073
Epoch: 3327 Loss: 0.046229925006628036
Epoch: 3328 Loss: 0.046230655163526535
Epoch: 3329 Loss: 0.04619079828262329
Epoch: 3330 Loss: 0.04614938795566559
Epoch: 3331 Loss: 0.04612233117222786
Epoch: 3332 Loss: 0.04609672352671623
Epoch: 3333 Loss: 0.046061042696237564
Epoc

Epoch: 3534 Loss: 0.04102354124188423
Epoch: 3535 Loss: 0.04098571091890335
Epoch: 3536 Loss: 0.04097873345017433
Epoch: 3537 Loss: 0.04096156731247902
Epoch: 3538 Loss: 0.04092172905802727
Epoch: 3539 Loss: 0.04090581461787224
Epoch: 3540 Loss: 0.04090036079287529
Epoch: 3541 Loss: 0.04086628183722496
Epoch: 3542 Loss: 0.040833085775375366
Epoch: 3543 Loss: 0.040823567658662796
Epoch: 3544 Loss: 0.04080010950565338
Epoch: 3545 Loss: 0.040767867118120193
Epoch: 3546 Loss: 0.040752798318862915
Epoch: 3547 Loss: 0.040732067078351974
Epoch: 3548 Loss: 0.04070955142378807
Epoch: 3549 Loss: 0.04067547991871834
Epoch: 3550 Loss: 0.040669359266757965
Epoch: 3551 Loss: 0.040639668703079224
Epoch: 3552 Loss: 0.04062286391854286
Epoch: 3553 Loss: 0.040606915950775146
Epoch: 3554 Loss: 0.040577035397291183
Epoch: 3555 Loss: 0.04055993631482124
Epoch: 3556 Loss: 0.040526241064071655
Epoch: 3557 Loss: 0.040502265095710754
Epoch: 3558 Loss: 0.04047401621937752
Epoch: 3559 Loss: 0.04045385867357254
E

Epoch: 3757 Loss: 0.03637547418475151
Epoch: 3758 Loss: 0.036354850977659225
Epoch: 3759 Loss: 0.03634076565504074
Epoch: 3760 Loss: 0.03632489964365959
Epoch: 3761 Loss: 0.036294061690568924
Epoch: 3762 Loss: 0.03627198189496994
Epoch: 3763 Loss: 0.03625207394361496
Epoch: 3764 Loss: 0.036251481622457504
Epoch: 3765 Loss: 0.036228012293577194
Epoch: 3766 Loss: 0.03620303422212601
Epoch: 3767 Loss: 0.03619087114930153
Epoch: 3768 Loss: 0.036166686564683914
Epoch: 3769 Loss: 0.036144111305475235
Epoch: 3770 Loss: 0.036125537008047104
Epoch: 3771 Loss: 0.03611847013235092
Epoch: 3772 Loss: 0.036092422902584076
Epoch: 3773 Loss: 0.03607438877224922
Epoch: 3774 Loss: 0.036069344729185104
Epoch: 3775 Loss: 0.03604636341333389
Epoch: 3776 Loss: 0.03602868691086769
Epoch: 3777 Loss: 0.03600994125008583
Epoch: 3778 Loss: 0.0359821580350399
Epoch: 3779 Loss: 0.035957954823970795
Epoch: 3780 Loss: 0.03595506027340889
Epoch: 3781 Loss: 0.035941317677497864
Epoch: 3782 Loss: 0.0359063595533371
Epo

Epoch: 3988 Loss: 0.03242975100874901
Epoch: 3989 Loss: 0.03239593282341957
Epoch: 3990 Loss: 0.03239523246884346
Epoch: 3991 Loss: 0.03237925469875336
Epoch: 3992 Loss: 0.03235245868563652
Epoch: 3993 Loss: 0.03233885020017624
Epoch: 3994 Loss: 0.03232496231794357
Epoch: 3995 Loss: 0.03231512010097504
Epoch: 3996 Loss: 0.03230408579111099
Epoch: 3997 Loss: 0.032284926623106
Epoch: 3998 Loss: 0.03226792439818382
Epoch: 3999 Loss: 0.03225061669945717
Epoch: 4000 Loss: 0.032235607504844666
Epoch: 4001 Loss: 0.03221702203154564
Epoch: 4002 Loss: 0.032198674976825714
Epoch: 4003 Loss: 0.032186780124902725
Epoch: 4004 Loss: 0.03218792751431465
Epoch: 4005 Loss: 0.03214992210268974
Epoch: 4006 Loss: 0.032148025929927826
Epoch: 4007 Loss: 0.03212510421872139
Epoch: 4008 Loss: 0.03211275488138199
Epoch: 4009 Loss: 0.032099686563014984
Epoch: 4010 Loss: 0.03209153190255165
Epoch: 4011 Loss: 0.032071229070425034
Epoch: 4012 Loss: 0.03205462545156479
Epoch: 4013 Loss: 0.03203925862908363
Epoch: 4

Epoch: 4231 Loss: 0.028973782435059547
Epoch: 4232 Loss: 0.02897770144045353
Epoch: 4233 Loss: 0.028948873281478882
Epoch: 4234 Loss: 0.028939906507730484
Epoch: 4235 Loss: 0.028924938291311264
Epoch: 4236 Loss: 0.028902225196361542
Epoch: 4237 Loss: 0.028901655226945877
Epoch: 4238 Loss: 0.028889477252960205
Epoch: 4239 Loss: 0.02887854538857937
Epoch: 4240 Loss: 0.02886258251965046
Epoch: 4241 Loss: 0.028848707675933838
Epoch: 4242 Loss: 0.028836537152528763
Epoch: 4243 Loss: 0.028823215514421463
Epoch: 4244 Loss: 0.028812255710363388
Epoch: 4245 Loss: 0.028808211907744408
Epoch: 4246 Loss: 0.028790168464183807
Epoch: 4247 Loss: 0.028771718963980675
Epoch: 4248 Loss: 0.028766578063368797
Epoch: 4249 Loss: 0.028746582567691803
Epoch: 4250 Loss: 0.028734520077705383
Epoch: 4251 Loss: 0.028725633397698402
Epoch: 4252 Loss: 0.028711823746562004
Epoch: 4253 Loss: 0.028696121647953987
Epoch: 4254 Loss: 0.0286845900118351
Epoch: 4255 Loss: 0.028674587607383728
Epoch: 4256 Loss: 0.0286577604

Epoch: 4456 Loss: 0.026314856484532356
Epoch: 4457 Loss: 0.02630128711462021
Epoch: 4458 Loss: 0.026292065158486366
Epoch: 4459 Loss: 0.02628333866596222
Epoch: 4460 Loss: 0.02627745270729065
Epoch: 4461 Loss: 0.02625497803092003
Epoch: 4462 Loss: 0.026247898116707802
Epoch: 4463 Loss: 0.026247601956129074
Epoch: 4464 Loss: 0.026234310120344162
Epoch: 4465 Loss: 0.026216713711619377
Epoch: 4466 Loss: 0.026210138574242592
Epoch: 4467 Loss: 0.026193570345640182
Epoch: 4468 Loss: 0.02617793157696724
Epoch: 4469 Loss: 0.026176560670137405
Epoch: 4470 Loss: 0.02616325207054615
Epoch: 4471 Loss: 0.026154523715376854
Epoch: 4472 Loss: 0.02614717371761799
Epoch: 4473 Loss: 0.026132220402359962
Epoch: 4474 Loss: 0.02612975612282753
Epoch: 4475 Loss: 0.026113077998161316
Epoch: 4476 Loss: 0.026105469092726707
Epoch: 4477 Loss: 0.026093335822224617
Epoch: 4478 Loss: 0.026083732023835182
Epoch: 4479 Loss: 0.02607128955423832
Epoch: 4480 Loss: 0.026062840595841408
Epoch: 4481 Loss: 0.02604152448475

Epoch: 4684 Loss: 0.024026215076446533
Epoch: 4685 Loss: 0.024006342515349388
Epoch: 4686 Loss: 0.023999959230422974
Epoch: 4687 Loss: 0.023988794535398483
Epoch: 4688 Loss: 0.02398332767188549
Epoch: 4689 Loss: 0.023967670276761055
Epoch: 4690 Loss: 0.023959139361977577
Epoch: 4691 Loss: 0.02395651862025261
Epoch: 4692 Loss: 0.023945121094584465
Epoch: 4693 Loss: 0.023933734744787216
Epoch: 4694 Loss: 0.023929839953780174
Epoch: 4695 Loss: 0.023912550881505013
Epoch: 4696 Loss: 0.02391219697892666
Epoch: 4697 Loss: 0.023899242281913757
Epoch: 4698 Loss: 0.023886237293481827
Epoch: 4699 Loss: 0.02388233318924904
Epoch: 4700 Loss: 0.023861704394221306
Epoch: 4701 Loss: 0.023860881105065346
Epoch: 4702 Loss: 0.02385392040014267
Epoch: 4703 Loss: 0.023843921720981598
Epoch: 4704 Loss: 0.023838628083467484
Epoch: 4705 Loss: 0.023827839642763138
Epoch: 4706 Loss: 0.023815130814909935
Epoch: 4707 Loss: 0.02380591444671154
Epoch: 4708 Loss: 0.023795045912265778
Epoch: 4709 Loss: 0.02378852851

Epoch: 4933 Loss: 0.021879399195313454
Epoch: 4934 Loss: 0.02187201753258705
Epoch: 4935 Loss: 0.021855216473340988
Epoch: 4936 Loss: 0.021857326850295067
Epoch: 4937 Loss: 0.021841546520590782
Epoch: 4938 Loss: 0.021829169243574142
Epoch: 4939 Loss: 0.02182536944746971
Epoch: 4940 Loss: 0.02181573212146759
Epoch: 4941 Loss: 0.02181282266974449
Epoch: 4942 Loss: 0.021799372509121895
Epoch: 4943 Loss: 0.021790603175759315
Epoch: 4944 Loss: 0.021787801757454872
Epoch: 4945 Loss: 0.021781612187623978
Epoch: 4946 Loss: 0.02177133411169052
Epoch: 4947 Loss: 0.02176348865032196
Epoch: 4948 Loss: 0.021753787994384766
Epoch: 4949 Loss: 0.02174709364771843
Epoch: 4950 Loss: 0.021739419549703598
Epoch: 4951 Loss: 0.021730242297053337
Epoch: 4952 Loss: 0.0217252466827631
Epoch: 4953 Loss: 0.021717535331845284
Epoch: 4954 Loss: 0.02170765958726406
Epoch: 4955 Loss: 0.021697845309972763
Epoch: 4956 Loss: 0.021697254851460457
Epoch: 4957 Loss: 0.021687101572752
Epoch: 4958 Loss: 0.021674465388059616

Epoch: 5151 Loss: 0.020233191549777985
Epoch: 5152 Loss: 0.0202312208712101
Epoch: 5153 Loss: 0.02022114023566246
Epoch: 5154 Loss: 0.020209120586514473
Epoch: 5155 Loss: 0.02021273970603943
Epoch: 5156 Loss: 0.020201150327920914
Epoch: 5157 Loss: 0.02019418030977249
Epoch: 5158 Loss: 0.020184654742479324
Epoch: 5159 Loss: 0.020179467275738716
Epoch: 5160 Loss: 0.020171409472823143
Epoch: 5161 Loss: 0.020166920498013496
Epoch: 5162 Loss: 0.020158683881163597
Epoch: 5163 Loss: 0.02015123888850212
Epoch: 5164 Loss: 0.020143887028098106
Epoch: 5165 Loss: 0.02013934776186943
Epoch: 5166 Loss: 0.020129460841417313
Epoch: 5167 Loss: 0.02012384496629238
Epoch: 5168 Loss: 0.020116621628403664
Epoch: 5169 Loss: 0.020109768956899643
Epoch: 5170 Loss: 0.020103594288229942
Epoch: 5171 Loss: 0.02009756676852703
Epoch: 5172 Loss: 0.02009248547255993
Epoch: 5173 Loss: 0.02007833868265152
Epoch: 5174 Loss: 0.020078131929039955
Epoch: 5175 Loss: 0.020069099962711334
Epoch: 5176 Loss: 0.0200565811246633

Epoch: 5384 Loss: 0.018699852749705315
Epoch: 5385 Loss: 0.01869138516485691
Epoch: 5386 Loss: 0.018687041476368904
Epoch: 5387 Loss: 0.01868104189634323
Epoch: 5388 Loss: 0.01867162622511387
Epoch: 5389 Loss: 0.018667694181203842
Epoch: 5390 Loss: 0.018655942752957344
Epoch: 5391 Loss: 0.018659796565771103
Epoch: 5392 Loss: 0.018652204424142838
Epoch: 5393 Loss: 0.018646322190761566
Epoch: 5394 Loss: 0.018633348867297173
Epoch: 5395 Loss: 0.018635470420122147
Epoch: 5396 Loss: 0.01862775720655918
Epoch: 5397 Loss: 0.01862041838467121
Epoch: 5398 Loss: 0.01861199550330639
Epoch: 5399 Loss: 0.01860739476978779
Epoch: 5400 Loss: 0.018601305782794952
Epoch: 5401 Loss: 0.018590513616800308
Epoch: 5402 Loss: 0.018585925921797752
Epoch: 5403 Loss: 0.01858443208038807
Epoch: 5404 Loss: 0.01857757940888405
Epoch: 5405 Loss: 0.018570970743894577
Epoch: 5406 Loss: 0.018566543236374855
Epoch: 5407 Loss: 0.018558232113718987
Epoch: 5408 Loss: 0.01855076476931572
Epoch: 5409 Loss: 0.018546890467405

Epoch: 5628 Loss: 0.017290763556957245
Epoch: 5629 Loss: 0.017283696681261063
Epoch: 5630 Loss: 0.01727217808365822
Epoch: 5631 Loss: 0.017270004376769066
Epoch: 5632 Loss: 0.017266027629375458
Epoch: 5633 Loss: 0.01725989580154419
Epoch: 5634 Loss: 0.017257874831557274
Epoch: 5635 Loss: 0.01724783144891262
Epoch: 5636 Loss: 0.017241302877664566
Epoch: 5637 Loss: 0.01724204234778881
Epoch: 5638 Loss: 0.01723247766494751
Epoch: 5639 Loss: 0.017231861129403114
Epoch: 5640 Loss: 0.017224883660674095
Epoch: 5641 Loss: 0.01721455715596676
Epoch: 5642 Loss: 0.017214691266417503
Epoch: 5643 Loss: 0.017205120995640755
Epoch: 5644 Loss: 0.017201924696564674
Epoch: 5645 Loss: 0.017196908593177795
Epoch: 5646 Loss: 0.017192093655467033
Epoch: 5647 Loss: 0.01718433015048504
Epoch: 5648 Loss: 0.01718112640082836
Epoch: 5649 Loss: 0.017173171043395996
Epoch: 5650 Loss: 0.017170831561088562
Epoch: 5651 Loss: 0.01716286689043045
Epoch: 5652 Loss: 0.017155010253190994
Epoch: 5653 Loss: 0.01715383306145

Epoch: 5871 Loss: 0.016045786440372467
Epoch: 5872 Loss: 0.016044143587350845
Epoch: 5873 Loss: 0.01603567786514759
Epoch: 5874 Loss: 0.01603173092007637
Epoch: 5875 Loss: 0.01602764055132866
Epoch: 5876 Loss: 0.016023965552449226
Epoch: 5877 Loss: 0.01601887121796608
Epoch: 5878 Loss: 0.016010310500860214
Epoch: 5879 Loss: 0.016011325642466545
Epoch: 5880 Loss: 0.016004197299480438
Epoch: 5881 Loss: 0.015997180715203285
Epoch: 5882 Loss: 0.015994852408766747
Epoch: 5883 Loss: 0.015989607200026512
Epoch: 5884 Loss: 0.015985164791345596
Epoch: 5885 Loss: 0.015979254618287086
Epoch: 5886 Loss: 0.01597266085445881
Epoch: 5887 Loss: 0.015970200300216675
Epoch: 5888 Loss: 0.015965426340699196
Epoch: 5889 Loss: 0.01595943421125412
Epoch: 5890 Loss: 0.01595577783882618
Epoch: 5891 Loss: 0.015950437635183334
Epoch: 5892 Loss: 0.01594569720327854
Epoch: 5893 Loss: 0.015941385179758072
Epoch: 5894 Loss: 0.015933966264128685
Epoch: 5895 Loss: 0.015933988615870476
Epoch: 5896 Loss: 0.0159291699528

Epoch: 6097 Loss: 0.015028704889118671
Epoch: 6098 Loss: 0.015025065280497074
Epoch: 6099 Loss: 0.015015948563814163
Epoch: 6100 Loss: 0.015018174424767494
Epoch: 6101 Loss: 0.015011139214038849
Epoch: 6102 Loss: 0.015007785521447659
Epoch: 6103 Loss: 0.01500008162111044
Epoch: 6104 Loss: 0.014995506964623928
Epoch: 6105 Loss: 0.014993499033153057
Epoch: 6106 Loss: 0.014988379552960396
Epoch: 6107 Loss: 0.014986393041908741
Epoch: 6108 Loss: 0.014980924315750599
Epoch: 6109 Loss: 0.014976853504776955
Epoch: 6110 Loss: 0.01496912445873022
Epoch: 6111 Loss: 0.014970213174819946
Epoch: 6112 Loss: 0.014969119802117348
Epoch: 6113 Loss: 0.014959045685827732
Epoch: 6114 Loss: 0.014955049380660057
Epoch: 6115 Loss: 0.0149490125477314
Epoch: 6116 Loss: 0.014946860261261463
Epoch: 6117 Loss: 0.014941887930035591
Epoch: 6118 Loss: 0.014937980100512505
Epoch: 6119 Loss: 0.014934795908629894
Epoch: 6120 Loss: 0.014929619617760181
Epoch: 6121 Loss: 0.014924228191375732
Epoch: 6122 Loss: 0.014921812

Epoch: 6309 Loss: 0.014165418222546577
Epoch: 6310 Loss: 0.014161315746605396
Epoch: 6311 Loss: 0.014161447994410992
Epoch: 6312 Loss: 0.014152958057820797
Epoch: 6313 Loss: 0.014149123802781105
Epoch: 6314 Loss: 0.014145893044769764
Epoch: 6315 Loss: 0.014140121638774872
Epoch: 6316 Loss: 0.014146457426249981
Epoch: 6317 Loss: 0.014134134165942669
Epoch: 6318 Loss: 0.014131737872958183
Epoch: 6319 Loss: 0.014128233306109905
Epoch: 6320 Loss: 0.01412456575781107
Epoch: 6321 Loss: 0.014117362909018993
Epoch: 6322 Loss: 0.014115510508418083
Epoch: 6323 Loss: 0.014111482538282871
Epoch: 6324 Loss: 0.014109800569713116
Epoch: 6325 Loss: 0.01410512812435627
Epoch: 6326 Loss: 0.014101044274866581
Epoch: 6327 Loss: 0.01409601978957653
Epoch: 6328 Loss: 0.01409097108989954
Epoch: 6329 Loss: 0.014089388772845268
Epoch: 6330 Loss: 0.014084987342357635
Epoch: 6331 Loss: 0.01408481691032648
Epoch: 6332 Loss: 0.014075635932385921
Epoch: 6333 Loss: 0.014073318801820278
Epoch: 6334 Loss: 0.0140722859

Epoch: 6528 Loss: 0.013366426341235638
Epoch: 6529 Loss: 0.013365685939788818
Epoch: 6530 Loss: 0.01335727609694004
Epoch: 6531 Loss: 0.013356171548366547
Epoch: 6532 Loss: 0.013351132161915302
Epoch: 6533 Loss: 0.013348739594221115
Epoch: 6534 Loss: 0.013345759361982346
Epoch: 6535 Loss: 0.01334298588335514
Epoch: 6536 Loss: 0.013337511569261551
Epoch: 6537 Loss: 0.013335003517568111
Epoch: 6538 Loss: 0.013330738991498947
Epoch: 6539 Loss: 0.013329456560313702
Epoch: 6540 Loss: 0.013326359912753105
Epoch: 6541 Loss: 0.013321898877620697
Epoch: 6542 Loss: 0.013315524905920029
Epoch: 6543 Loss: 0.013314968906342983
Epoch: 6544 Loss: 0.013308191671967506
Epoch: 6545 Loss: 0.013307230547070503
Epoch: 6546 Loss: 0.013305974192917347
Epoch: 6547 Loss: 0.013297590427100658
Epoch: 6548 Loss: 0.013299847021698952
Epoch: 6549 Loss: 0.013294312171638012
Epoch: 6550 Loss: 0.013289129361510277
Epoch: 6551 Loss: 0.013286015950143337
Epoch: 6552 Loss: 0.013284986838698387
Epoch: 6553 Loss: 0.0132797

Epoch: 6764 Loss: 0.012589935213327408
Epoch: 6765 Loss: 0.012587383389472961
Epoch: 6766 Loss: 0.012584198266267776
Epoch: 6767 Loss: 0.012581698596477509
Epoch: 6768 Loss: 0.012576569803059101
Epoch: 6769 Loss: 0.012573698535561562
Epoch: 6770 Loss: 0.012572591193020344
Epoch: 6771 Loss: 0.012567861005663872
Epoch: 6772 Loss: 0.012563195079565048
Epoch: 6773 Loss: 0.012562286108732224
Epoch: 6774 Loss: 0.012559575960040092
Epoch: 6775 Loss: 0.012555455788969994
Epoch: 6776 Loss: 0.012553185224533081
Epoch: 6777 Loss: 0.012550389394164085
Epoch: 6778 Loss: 0.012547171674668789
Epoch: 6779 Loss: 0.012544000521302223
Epoch: 6780 Loss: 0.012542673386633396
Epoch: 6781 Loss: 0.012538195587694645
Epoch: 6782 Loss: 0.012534359470009804
Epoch: 6783 Loss: 0.012532667256891727
Epoch: 6784 Loss: 0.012528969906270504
Epoch: 6785 Loss: 0.012527174316346645
Epoch: 6786 Loss: 0.012524471618235111
Epoch: 6787 Loss: 0.012518671341240406
Epoch: 6788 Loss: 0.012516488321125507
Epoch: 6789 Loss: 0.01251

Epoch: 7005 Loss: 0.01187939289957285
Epoch: 7006 Loss: 0.01187761127948761
Epoch: 7007 Loss: 0.011873701587319374
Epoch: 7008 Loss: 0.01187161821871996
Epoch: 7009 Loss: 0.011867799796164036
Epoch: 7010 Loss: 0.011865764856338501
Epoch: 7011 Loss: 0.011861096136271954
Epoch: 7012 Loss: 0.011858722195029259
Epoch: 7013 Loss: 0.011855991557240486
Epoch: 7014 Loss: 0.011852245777845383
Epoch: 7015 Loss: 0.011848997324705124
Epoch: 7016 Loss: 0.011847641319036484
Epoch: 7017 Loss: 0.011843672022223473
Epoch: 7018 Loss: 0.01184257585555315
Epoch: 7019 Loss: 0.01183764822781086
Epoch: 7020 Loss: 0.011838174425065517
Epoch: 7021 Loss: 0.011835546232759953
Epoch: 7022 Loss: 0.01183105818927288
Epoch: 7023 Loss: 0.01182924397289753
Epoch: 7024 Loss: 0.011824837885797024
Epoch: 7025 Loss: 0.011822567321360111
Epoch: 7026 Loss: 0.011821674183011055
Epoch: 7027 Loss: 0.011817451566457748
Epoch: 7028 Loss: 0.011814582161605358
Epoch: 7029 Loss: 0.011814801022410393
Epoch: 7030 Loss: 0.011809095740

Epoch: 7261 Loss: 0.011194190010428429
Epoch: 7262 Loss: 0.011197191663086414
Epoch: 7263 Loss: 0.011194268241524696
Epoch: 7264 Loss: 0.011191456578671932
Epoch: 7265 Loss: 0.011185770854353905
Epoch: 7266 Loss: 0.011184204369783401
Epoch: 7267 Loss: 0.011181648820638657
Epoch: 7268 Loss: 0.011179633438587189
Epoch: 7269 Loss: 0.011177366599440575
Epoch: 7270 Loss: 0.011173028498888016
Epoch: 7271 Loss: 0.011171388439834118
Epoch: 7272 Loss: 0.011169611476361752
Epoch: 7273 Loss: 0.011166904121637344
Epoch: 7274 Loss: 0.011164583265781403
Epoch: 7275 Loss: 0.01116247195750475
Epoch: 7276 Loss: 0.011158573441207409
Epoch: 7277 Loss: 0.011158247478306293
Epoch: 7278 Loss: 0.011155553162097931
Epoch: 7279 Loss: 0.01115176361054182
Epoch: 7280 Loss: 0.01114979013800621
Epoch: 7281 Loss: 0.01114706415683031
Epoch: 7282 Loss: 0.011143598705530167
Epoch: 7283 Loss: 0.011142635717988014
Epoch: 7284 Loss: 0.011138666421175003
Epoch: 7285 Loss: 0.011134613305330276
Epoch: 7286 Loss: 0.011133669

Epoch: 7504 Loss: 0.010610378347337246
Epoch: 7505 Loss: 0.010607774369418621
Epoch: 7506 Loss: 0.010606304742395878
Epoch: 7507 Loss: 0.010602367110550404
Epoch: 7508 Loss: 0.01060006394982338
Epoch: 7509 Loss: 0.010599305853247643
Epoch: 7510 Loss: 0.010595191270112991
Epoch: 7511 Loss: 0.010592656210064888
Epoch: 7512 Loss: 0.010591487400233746
Epoch: 7513 Loss: 0.010587477125227451
Epoch: 7514 Loss: 0.010586569085717201
Epoch: 7515 Loss: 0.010587042197585106
Epoch: 7516 Loss: 0.01058153435587883
Epoch: 7517 Loss: 0.010580720379948616
Epoch: 7518 Loss: 0.01057907473295927
Epoch: 7519 Loss: 0.010573097504675388
Epoch: 7520 Loss: 0.010572236962616444
Epoch: 7521 Loss: 0.010570550337433815
Epoch: 7522 Loss: 0.010569427162408829
Epoch: 7523 Loss: 0.01056636031717062
Epoch: 7524 Loss: 0.010564183816313744
Epoch: 7525 Loss: 0.010560691356658936
Epoch: 7526 Loss: 0.010558964684605598
Epoch: 7527 Loss: 0.010558449663221836
Epoch: 7528 Loss: 0.010553705506026745
Epoch: 7529 Loss: 0.010552642

Epoch: 7718 Loss: 0.010138963349163532
Epoch: 7719 Loss: 0.010134906508028507
Epoch: 7720 Loss: 0.010132615454494953
Epoch: 7721 Loss: 0.0101305628195405
Epoch: 7722 Loss: 0.010128533467650414
Epoch: 7723 Loss: 0.010126765817403793
Epoch: 7724 Loss: 0.01012350432574749
Epoch: 7725 Loss: 0.010121777653694153
Epoch: 7726 Loss: 0.01012105867266655
Epoch: 7727 Loss: 0.010120195336639881
Epoch: 7728 Loss: 0.010115176439285278
Epoch: 7729 Loss: 0.010114210657775402
Epoch: 7730 Loss: 0.010111506097018719
Epoch: 7731 Loss: 0.010110840201377869
Epoch: 7732 Loss: 0.010106265544891357
Epoch: 7733 Loss: 0.010105743072926998
Epoch: 7734 Loss: 0.010104103945195675
Epoch: 7735 Loss: 0.010102014988660812
Epoch: 7736 Loss: 0.01010082010179758
Epoch: 7737 Loss: 0.010097949765622616
Epoch: 7738 Loss: 0.010096301324665546
Epoch: 7739 Loss: 0.010094310157001019
Epoch: 7740 Loss: 0.01009170338511467
Epoch: 7741 Loss: 0.01009046658873558
Epoch: 7742 Loss: 0.010087434202432632
Epoch: 7743 Loss: 0.010083480738

Epoch: 7951 Loss: 0.009665483608841896
Epoch: 7952 Loss: 0.009662380442023277
Epoch: 7953 Loss: 0.009659795090556145
Epoch: 7954 Loss: 0.009658788330852985
Epoch: 7955 Loss: 0.00965789332985878
Epoch: 7956 Loss: 0.009654195047914982
Epoch: 7957 Loss: 0.009653333574533463
Epoch: 7958 Loss: 0.00965087115764618
Epoch: 7959 Loss: 0.009648791514337063
Epoch: 7960 Loss: 0.00964815728366375
Epoch: 7961 Loss: 0.009646872989833355
Epoch: 7962 Loss: 0.009643220342695713
Epoch: 7963 Loss: 0.009642616845667362
Epoch: 7964 Loss: 0.009639713913202286
Epoch: 7965 Loss: 0.00963823962956667
Epoch: 7966 Loss: 0.009637098759412766
Epoch: 7967 Loss: 0.009633993729948997
Epoch: 7968 Loss: 0.009631515480577946
Epoch: 7969 Loss: 0.009629945270717144
Epoch: 7970 Loss: 0.009629585780203342
Epoch: 7971 Loss: 0.00962627399712801
Epoch: 7972 Loss: 0.009624638594686985
Epoch: 7973 Loss: 0.009622924961149693
Epoch: 7974 Loss: 0.009618829004466534
Epoch: 7975 Loss: 0.009620166383683681
Epoch: 7976 Loss: 0.0096168601

Epoch: 8174 Loss: 0.009250068105757236
Epoch: 8175 Loss: 0.009249541908502579
Epoch: 8176 Loss: 0.009246520698070526
Epoch: 8177 Loss: 0.009245267137885094
Epoch: 8178 Loss: 0.009243453852832317
Epoch: 8179 Loss: 0.009242748841643333
Epoch: 8180 Loss: 0.009240205399692059
Epoch: 8181 Loss: 0.009237131103873253
Epoch: 8182 Loss: 0.00923592783510685
Epoch: 8183 Loss: 0.009233728982508183
Epoch: 8184 Loss: 0.009232193231582642
Epoch: 8185 Loss: 0.009229416958987713
Epoch: 8186 Loss: 0.00922951940447092
Epoch: 8187 Loss: 0.009226806461811066
Epoch: 8188 Loss: 0.009224948473274708
Epoch: 8189 Loss: 0.009223868139088154
Epoch: 8190 Loss: 0.009221035055816174
Epoch: 8191 Loss: 0.009220867417752743
Epoch: 8192 Loss: 0.009216688573360443
Epoch: 8193 Loss: 0.009216198697686195
Epoch: 8194 Loss: 0.009214724414050579
Epoch: 8195 Loss: 0.009211210533976555
Epoch: 8196 Loss: 0.009210842661559582
Epoch: 8197 Loss: 0.00920961145311594
Epoch: 8198 Loss: 0.009207278490066528
Epoch: 8199 Loss: 0.00920524

Epoch: 8425 Loss: 0.008820919319987297
Epoch: 8426 Loss: 0.008816520683467388
Epoch: 8427 Loss: 0.008816472254693508
Epoch: 8428 Loss: 0.008816269226372242
Epoch: 8429 Loss: 0.0088121946901083
Epoch: 8430 Loss: 0.008811021223664284
Epoch: 8431 Loss: 0.008810434490442276
Epoch: 8432 Loss: 0.00880884937942028
Epoch: 8433 Loss: 0.008804796263575554
Epoch: 8434 Loss: 0.008805575780570507
Epoch: 8435 Loss: 0.008803407661616802
Epoch: 8436 Loss: 0.008801874704658985
Epoch: 8437 Loss: 0.008800886571407318
Epoch: 8438 Loss: 0.008799172006547451
Epoch: 8439 Loss: 0.008795983158051968
Epoch: 8440 Loss: 0.008795181289315224
Epoch: 8441 Loss: 0.008794265799224377
Epoch: 8442 Loss: 0.008791081607341766
Epoch: 8443 Loss: 0.00879112258553505
Epoch: 8444 Loss: 0.0087890001013875
Epoch: 8445 Loss: 0.00878597330302
Epoch: 8446 Loss: 0.008785166777670383
Epoch: 8447 Loss: 0.008784935809671879
Epoch: 8448 Loss: 0.0087818568572402
Epoch: 8449 Loss: 0.008781393058598042
Epoch: 8450 Loss: 0.00877951364964246

Epoch: 8678 Loss: 0.008418380282819271
Epoch: 8679 Loss: 0.00841765757650137
Epoch: 8680 Loss: 0.008414794690907001
Epoch: 8681 Loss: 0.008413182571530342
Epoch: 8682 Loss: 0.00841265358030796
Epoch: 8683 Loss: 0.008410787209868431
Epoch: 8684 Loss: 0.008409421890974045
Epoch: 8685 Loss: 0.008407458662986755
Epoch: 8686 Loss: 0.008405431173741817
Epoch: 8687 Loss: 0.008404751308262348
Epoch: 8688 Loss: 0.00840187817811966
Epoch: 8689 Loss: 0.008401352912187576
Epoch: 8690 Loss: 0.008399050682783127
Epoch: 8691 Loss: 0.008398320525884628
Epoch: 8692 Loss: 0.008396465331315994
Epoch: 8693 Loss: 0.008395661599934101
Epoch: 8694 Loss: 0.008393727242946625
Epoch: 8695 Loss: 0.0083918496966362
Epoch: 8696 Loss: 0.008390294387936592
Epoch: 8697 Loss: 0.008389471098780632
Epoch: 8698 Loss: 0.008387311361730099
Epoch: 8699 Loss: 0.008385577239096165
Epoch: 8700 Loss: 0.008386206813156605
Epoch: 8701 Loss: 0.008382730185985565
Epoch: 8702 Loss: 0.008382565341889858
Epoch: 8703 Loss: 0.0083805695

Epoch: 8925 Loss: 0.008054996840655804
Epoch: 8926 Loss: 0.00805528461933136
Epoch: 8927 Loss: 0.008054076693952084
Epoch: 8928 Loss: 0.00805126503109932
Epoch: 8929 Loss: 0.008050928823649883
Epoch: 8930 Loss: 0.008049996569752693
Epoch: 8931 Loss: 0.008047593757510185
Epoch: 8932 Loss: 0.008047277107834816
Epoch: 8933 Loss: 0.0080446507781744
Epoch: 8934 Loss: 0.008043044246733189
Epoch: 8935 Loss: 0.008042884059250355
Epoch: 8936 Loss: 0.008040221408009529
Epoch: 8937 Loss: 0.00803910568356514
Epoch: 8938 Loss: 0.008038429543375969
Epoch: 8939 Loss: 0.008036138489842415
Epoch: 8940 Loss: 0.008035155944526196
Epoch: 8941 Loss: 0.008033661171793938
Epoch: 8942 Loss: 0.008031659759581089
Epoch: 8943 Loss: 0.008031562902033329
Epoch: 8944 Loss: 0.008029801771044731
Epoch: 8945 Loss: 0.00802853424102068
Epoch: 8946 Loss: 0.008026680909097195
Epoch: 8947 Loss: 0.008024398237466812
Epoch: 8948 Loss: 0.008023283444344997
Epoch: 8949 Loss: 0.008023404516279697
Epoch: 8950 Loss: 0.00802112929

Epoch: 9139 Loss: 0.007766424678266048
Epoch: 9140 Loss: 0.007764000911265612
Epoch: 9141 Loss: 0.00776378670707345
Epoch: 9142 Loss: 0.007761605549603701
Epoch: 9143 Loss: 0.007759581319987774
Epoch: 9144 Loss: 0.007759136147797108
Epoch: 9145 Loss: 0.007757973857223988
Epoch: 9146 Loss: 0.007756608072668314
Epoch: 9147 Loss: 0.007755705155432224
Epoch: 9148 Loss: 0.007753607351332903
Epoch: 9149 Loss: 0.007751635741442442
Epoch: 9150 Loss: 0.007751920726150274
Epoch: 9151 Loss: 0.007749869022518396
Epoch: 9152 Loss: 0.007748892065137625
Epoch: 9153 Loss: 0.00774673605337739
Epoch: 9154 Loss: 0.0077453190460801125
Epoch: 9155 Loss: 0.0077445777133107185
Epoch: 9156 Loss: 0.007744357455521822
Epoch: 9157 Loss: 0.007740732282400131
Epoch: 9158 Loss: 0.007741034962236881
Epoch: 9159 Loss: 0.007739285472780466
Epoch: 9160 Loss: 0.0077377608977258205
Epoch: 9161 Loss: 0.00773654505610466
Epoch: 9162 Loss: 0.00773664703592658
Epoch: 9163 Loss: 0.007735050283372402
Epoch: 9164 Loss: 0.007732

Epoch: 9353 Loss: 0.0074927001260221004
Epoch: 9354 Loss: 0.007492307107895613
Epoch: 9355 Loss: 0.007490573450922966
Epoch: 9356 Loss: 0.007490106392651796
Epoch: 9357 Loss: 0.007490082643926144
Epoch: 9358 Loss: 0.007487477269023657
Epoch: 9359 Loss: 0.007486065849661827
Epoch: 9360 Loss: 0.00748487701639533
Epoch: 9361 Loss: 0.007483200170099735
Epoch: 9362 Loss: 0.0074826618656516075
Epoch: 9363 Loss: 0.0074811577796936035
Epoch: 9364 Loss: 0.007481059059500694
Epoch: 9365 Loss: 0.007478817831724882
Epoch: 9366 Loss: 0.00747779943048954
Epoch: 9367 Loss: 0.007476067170500755
Epoch: 9368 Loss: 0.007473818026483059
Epoch: 9369 Loss: 0.007473824545741081
Epoch: 9370 Loss: 0.007472689729183912
Epoch: 9371 Loss: 0.007472568657249212
Epoch: 9372 Loss: 0.007470408454537392
Epoch: 9373 Loss: 0.007469702046364546
Epoch: 9374 Loss: 0.007466964889317751
Epoch: 9375 Loss: 0.007467251271009445
Epoch: 9376 Loss: 0.007465834263712168
Epoch: 9377 Loss: 0.00746415089815855
Epoch: 9378 Loss: 0.00746

Epoch: 9565 Loss: 0.0072406078688800335
Epoch: 9566 Loss: 0.007240116596221924
Epoch: 9567 Loss: 0.007238602265715599
Epoch: 9568 Loss: 0.0072365375235676765
Epoch: 9569 Loss: 0.007235923781991005
Epoch: 9570 Loss: 0.007235110271722078
Epoch: 9571 Loss: 0.007232996169477701
Epoch: 9572 Loss: 0.007233030628412962
Epoch: 9573 Loss: 0.007230693474411964
Epoch: 9574 Loss: 0.007229445036500692
Epoch: 9575 Loss: 0.00722972396761179
Epoch: 9576 Loss: 0.007227480877190828
Epoch: 9577 Loss: 0.0072268955409526825
Epoch: 9578 Loss: 0.007226452697068453
Epoch: 9579 Loss: 0.007224913686513901
Epoch: 9580 Loss: 0.007223749533295631
Epoch: 9581 Loss: 0.007222752086818218
Epoch: 9582 Loss: 0.007220538333058357
Epoch: 9583 Loss: 0.007219329942017794
Epoch: 9584 Loss: 0.007218895945698023
Epoch: 9585 Loss: 0.007217542268335819
Epoch: 9586 Loss: 0.007215531077235937
Epoch: 9587 Loss: 0.007215372286736965
Epoch: 9588 Loss: 0.007214013021439314
Epoch: 9589 Loss: 0.00721253314986825
Epoch: 9590 Loss: 0.0072

Epoch: 9779 Loss: 0.007000849116593599
Epoch: 9780 Loss: 0.0069996449165046215
Epoch: 9781 Loss: 0.006997883319854736
Epoch: 9782 Loss: 0.006997379008680582
Epoch: 9783 Loss: 0.006996979936957359
Epoch: 9784 Loss: 0.006995642092078924
Epoch: 9785 Loss: 0.006994007620960474
Epoch: 9786 Loss: 0.006993980146944523
Epoch: 9787 Loss: 0.006991949398070574
Epoch: 9788 Loss: 0.006991394329816103
Epoch: 9789 Loss: 0.006989946588873863
Epoch: 9790 Loss: 0.006990429945290089
Epoch: 9791 Loss: 0.006987639702856541
Epoch: 9792 Loss: 0.006986848544329405
Epoch: 9793 Loss: 0.006985087413340807
Epoch: 9794 Loss: 0.006985160056501627
Epoch: 9795 Loss: 0.006983291357755661
Epoch: 9796 Loss: 0.006982609163969755
Epoch: 9797 Loss: 0.006980978883802891
Epoch: 9798 Loss: 0.006980245467275381
Epoch: 9799 Loss: 0.006979445461183786
Epoch: 9800 Loss: 0.0069784848019480705
Epoch: 9801 Loss: 0.006977461744099855
Epoch: 9802 Loss: 0.006976526230573654
Epoch: 9803 Loss: 0.006975486874580383
Epoch: 9804 Loss: 0.006

In [ ]:
# Output now
testX = torch.Tensor([binary_encode(i, NUM_DIGITS) for i in range(1, 101)])
with torch.no_grad():
    testY = model(testX)
predictions = zip(range(1, 101), list(testY.max(1)[1].data.tolist()))

print([fizz_buzz_decode(i, x) for (i, x) in predictions])

In [ ]:
print(np.sum(testY.max(1)[1].numpy() == np.array([fizz_buzz_encode(i) for i in range(1,101)])))
testY.max(1)[1].numpy() == np.array([fizz_buzz_encode(i) for i in range(1,101)])